#!/bin/bash

#Realizar un script que reciba dos números por parámetro y muestre un mensaje
#indicando si ambos números son iguales, si el primer número es mayor o si el segundo
#número es mayor. 
  
if  [ $1  -gt  $2 ]; then 
 
    echo "El primer número ($1) es mayor ($2) ";
else  

 

    echo "El segundo número ($2) es mayor que el primero ($1) ";
fi
if [ $1 -eq $2 ]; then
    echo "Ambos numeros son iguales";
fi
